steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/lucky-ai-repo/train-image:${_TAG}',
    '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/lucky-ai-repo/train-image:latest',
    '-f', 'dockerfiles/train.dockerfile',
    '.'
  ]

images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/lucky-ai-repo/train-image:${_TAG}'
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/lucky-ai-repo/train-image:latest'

substitutions:
  _TAG: "dev"

options:
  logging: CLOUD_LOGGING_ONLY
